#!/usr/bin/python
"""Amulet tests on a basic openvswitch ODL deployment on trusty-kilo."""

from basic_deployment import OVSODLBasicDeployment

if __name__ == '__main__':
    deployment = OVSODLBasicDeployment(series='trusty',
                                       openstack='cloud:trusty-kilo',
                                       source='cloud:trusty-updates/kilo')
    deployment.run_tests()
