#!/usr/bin/python
"""Amulet tests on a basic openvswitch ODL deployment on trusty-mitaka."""

from basic_deployment import OVSODLBasicDeployment

if __name__ == '__main__':
    deployment = OVSODLBasicDeployment(series='trusty',
                                       openstack='cloud:trusty-mitaka',
                                       source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
