#!/usr/bin/python
"""Amulet tests on a basic openvswitch ODL deployment on xenial-mitaka."""

from basic_deployment import OVSODLBasicDeployment

if __name__ == '__main__':
    deployment = OVSODLBasicDeployment(series='xenial',
                                       odl_version='beryllium')
    deployment.run_tests()
