#!/usr/bin/python
"""Amulet tests on a basic cisco-vpp deployment on xenial-mitaka."""

from basic_deployment import OVSODLBasicDeployment

if __name__ == '__main__':
    deployment = OVSODLBasicDeployment(series='xenial')
    deployment.run_tests()
